name: sentiment_classification
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.serve
      args:
        model_data: models/cardiffnlp/twitter-roberta-base-sentiment-latest
    ports:
      - "1234:1234"
