FROM python:3

ARG model_data

WORKDIR /app
COPY src .
COPY ${model_data} model/data

ENV MODEL_DIR=model/data
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=1234
ENV PYTHONPATH=/app

RUN apt-get install gcc -y
RUN pip install -r requirements.txt

EXPOSE 1234

CMD ["flask", "run", "--debug"]
