defaults:
  - train
  - _self_

training_args:
  do_train: false
  do_eval: false
  do_predict: true
  save_steps: 10
  eval_steps: 10
  logging_steps: 10
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  max_steps: 20
